# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0006_list_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='rest_pics'),
        ),
        migrations.AlterField(
            model_name='list',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='rest_pics'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='restaurants',
            field=models.ManyToManyField(to='rest_lists.Restaurant'),
        ),
    ]
