# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0007_auto_20160408_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(to='rest_lists.List'),
        ),
    ]
