# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0010_auto_20160409_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
