# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0011_auto_20160409_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='url',
            new_name='openrice',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
