# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0012_auto_20160410_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='openrice',
            new_name='url',
        ),
    ]
