# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0013_auto_20160410_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default',
        ),
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
