# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0014_auto_20160410_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='mirko', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='zhao', max_length=255),
            preserve_default=False,
        ),
    ]
