# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_lists', '0015_auto_20160410_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='restaurants',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
